http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth:
  jwt:
    accessTokenTTL: 15m
    refreshTokenTTL: 720h
  secretCodeLifetime: 5m
  verificationCodeLength: 6

smtp:
  host: "smtp.gmail.com"
  port: 587

mongodb:
  username: vanya
  databaseName: services

email:
  templates:
    login_notification: "./templates/login_notification.html"
  subjects:
    login_notification: "Уведомление о входе в аккаунт"